'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreateQuestion
    
    '''<summary>
    '''divStandard1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStandard1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lnkStandard1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkStandard1 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divStandard2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStandard2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lnkStandard2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkStandard2 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divStandard3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStandard3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lnkStandard3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkStandard3 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divAnswertype3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAnswertype3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lnkAnswertype3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAnswertype3 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divAnswertype2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAnswertype2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lnkAnswertype2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAnswertype2 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divAnswertype4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAnswertype4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lnkAnswertype4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAnswertype4 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divAnswertype1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAnswertype1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lnkAnswertype1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAnswertype1 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtQuestionStem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuestionStem As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxWatermarkExtender2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxWatermarkExtender2 As Global.AjaxControlToolkit.TextBoxWatermarkExtender
    
    '''<summary>
    '''divMultipleChoices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMultipleChoices As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''rbtnChoiceA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnChoiceA As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txtChoiceA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChoiceA As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxWatermarkExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxWatermarkExtender1 As Global.AjaxControlToolkit.TextBoxWatermarkExtender
    
    '''<summary>
    '''rbtnChoiceB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnChoiceB As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txtChoiceB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChoiceB As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxWatermarkExtender3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxWatermarkExtender3 As Global.AjaxControlToolkit.TextBoxWatermarkExtender
    
    '''<summary>
    '''rbtnChoiceC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnChoiceC As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txtChoiceC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChoiceC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxWatermarkExtender4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxWatermarkExtender4 As Global.AjaxControlToolkit.TextBoxWatermarkExtender
    
    '''<summary>
    '''rbtnChoiceD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnChoiceD As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txtChoiceD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChoiceD As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxWatermarkExtender5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxWatermarkExtender5 As Global.AjaxControlToolkit.TextBoxWatermarkExtender
    
    '''<summary>
    '''divMultiChoices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMultiChoices As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkbtnChoiceA1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbtnChoiceA1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtChoiceA1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChoiceA1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxWatermarkExtender6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxWatermarkExtender6 As Global.AjaxControlToolkit.TextBoxWatermarkExtender
    
    '''<summary>
    '''chkbtnChoiceB1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbtnChoiceB1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtChoiceB1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChoiceB1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxWatermarkExtender7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxWatermarkExtender7 As Global.AjaxControlToolkit.TextBoxWatermarkExtender
    
    '''<summary>
    '''chkbtnChoiceC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbtnChoiceC1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtChoiceC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChoiceC1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxWatermarkExtender8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxWatermarkExtender8 As Global.AjaxControlToolkit.TextBoxWatermarkExtender
    
    '''<summary>
    '''chkbtnChoiceD1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbtnChoiceD1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtChoiceD1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChoiceD1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxWatermarkExtender9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxWatermarkExtender9 As Global.AjaxControlToolkit.TextBoxWatermarkExtender
    
    '''<summary>
    '''divTrueFalse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTrueFalse As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''rbtnTrue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnTrue As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rbtnFalse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnFalse As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''divShortAns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divShortAns As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtShortAns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShortAns As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxWatermarkExtender10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxWatermarkExtender10 As Global.AjaxControlToolkit.TextBoxWatermarkExtender
    
    '''<summary>
    '''lnkbtnAddImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnAddImage As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkbtnAddExplanation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnAddExplanation As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkCreateQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCreateQuestion As Global.System.Web.UI.WebControls.LinkButton
End Class
