'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class QBFilters
    
    '''<summary>
    '''lnkGradefilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkGradefilter As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkSubjectfilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSubjectfilter As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkStandardfilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkStandardfilter As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkQIDfilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkQIDfilter As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkQuestiontype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkQuestiontype As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSearch As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkShowall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkShowall As Global.System.Web.UI.WebControls.LinkButton
End Class
