'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class QBOtherfeatures
    
    '''<summary>
    '''divAddExplanation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAddExplanation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtExplanation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExplanation As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkOK As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCancel As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divAddImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAddImage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''fupldImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fupldImage As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lnkOK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkOK1 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkCancel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCancel1 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divStandardFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStandardFilter As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlStandards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStandards As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lnkOK2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkOK2 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkCancel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCancel2 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divSubjectFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSubjectFilter As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlSubjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSubjects As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lnkOK3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkOK3 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkCancel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCancel3 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divGradeFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGradeFilter As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlGrades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGrades As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lnkOK4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkOK4 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkCancel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCancel4 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divQIDFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divQIDFilter As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlQIDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQIDs As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lnkOK5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkOK5 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkCancel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCancel5 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divQTypeFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divQTypeFilter As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlQTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQTypes As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lnkOK6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkOK6 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkCancel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCancel6 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divSearchFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSearchFilter As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''rblSearchtypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblSearchtypes As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtSearchTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchTerm As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkOK7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkOK7 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkCancel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCancel7 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label
End Class
