'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class QuestionBox
    
    '''<summary>
    '''divQuestionNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divQuestionNo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lnkEditQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkEditQuestion As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkDeleteQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDeleteQuestion As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkDuplicateQID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDuplicateQID As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAddtoAssessment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddtoAssessment As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divQSnapshot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divQSnapshot As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divEditQSnapshot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEditQSnapshot As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtQuestionSnapshot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuestionSnapshot As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStandard As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
